spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jrtp
    username: root
    password: 4562
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect


server:
  port: 2020